### PR TITLE
User/mjh/open bc segments

### PR DESCRIPTION
**Pull request by MJHarrison-GFDL**
I hard-wired the code so that if the "Flather" flag is turned on, it expects U,V,SSH in that order in the obc_segment_data parameter. Obviously this is an error-prone strategy so this needs work. Also, need to derive BT velocities from BC flow.

### CODE REVIEW

**Comment by MJHarrison-GFDL** [comment]
Here is a sample brushcutter file ( 1 time level) which will work with the CCS1 grid.

ftp://ftp.gfdl.noaa.gov/pub/mjh/obc_monthly_CCS1.nc

and corresponding MOM_input lines:

! === OBC options ===
OBC_NUMBER_OF_SEGMENTS = 3      ! [Integer] The number of open boundary segments.
OBC_SEGMENT_001 = "J=N,I=N:-1,FLATHER" ! Don't need to go to N+1 because it's in the land.
OBC_SEGMENT_002 = "J=0,I=-1:N,FLATHER" ! Don't need to go to N+1 because it's in the land.
OBC_SEGMENT_003 = "I=0,J=N:0,FLATHER"
OBC_CONFIG = "SEGMENTS"
OBC_SEGMENT_001_DATA = "U=file:obc_monthly_CCS1.nc(u),V=file:obc_monthly_CCS1.nc(v),SSH=file:obc_monthly_CCS1.nc(zeta)"
OBC_SEGMENT_002_DATA = "U=file:obc_monthly_CCS1.nc(u),V=file:obc_monthly_CCS1.nc(v),SSH=file:obc_monthly_CCS1.nc(zeta)"
OBC_SEGMENT_003_DATA = "U=file:obc_monthly_CCS1.nc(u),V=file:obc_monthly_CCS1.nc(v),SSH=file:obc_monthly_CCS1.nc(zeta)"

**Comment by kshedstrom** [comment]
We changed things so that the code internally extends to i=-1. We no longer want to do it in MOM_input:
! === OBC options ===
OBC_NUMBER_OF_SEGMENTS = 3 ! [Integer] The number of open boundary segments.
OBC_SEGMENT_001 = "J=N,I=N:0,FLATHER"
OBC_SEGMENT_002 = "J=0,I=0:N,FLATHER"
OBC_SEGMENT_003 = "I=0,J=N:0,FLATHER"

Also, for 3D flow, this should work (someday):
! === OBC options ===
OBC_NUMBER_OF_SEGMENTS = 3 ! [Integer] The number of open boundary segments.
OBC_SEGMENT_001 = "J=N,I=N:0,FLATHER, ORLANSKI, NUDGED"
OBC_SEGMENT_002 = "J=0,I=0:N,FLATHER, ORLANSKI, NUDGED"
OBC_SEGMENT_003 = "I=0,J=N:0,FLATHER, ORLANSKI, NUDGED"
and the "NUDGED" is a cue that we'll need 3D boundary values. There's some code now for u,v, with tracers needed someday too. Not sure how we'll determine what to do about tracers and/or layer thicknesses.

**Comment by MJHarrison-GFDL** [comment]
@kshedstrom I like the 0-index convention for MOM_input , i.e. J=0 corresponds to the southern boundary and J=N is the northern one.  Otherwise it should be J=1 and J=N+1 with fortran indices.  It's confusing to take 1,N to mean the same thing (i.e. the outer boundaries)

We have 3d boundary values for tracers and velocities and 2-d SSH now stored in the segment_data object. What is needed is a generic interface to map the buffer data to the model variables, e.g. 

OBC_segment_to_grid(OBC,'U',U_data)

returns boundary data on the local model grid domain. UBAR could be a derived quantity from U, or it could be in MOM_input.  Thoughts on allowing for both options?

The layer thicknesses on remapped segments will be the same as the model .  

https://github.com/ESMG/MOM6/blob/dev/master/src/parameterizations/vertical/MOM_ALE_sponge.F90

is damping thicknesses to external data.  This makes sense if the *regridding* parameters for the external model are consistent.

**Comment by kshedstrom** [comment]
I'm getting this from circle_obcs:

> FATAL from PE     0: MOM_open_boundary, initialize_segment_data: Need three inputs for Flather

Fair enough, switching to just ORLANSKI:
> At line 1372 of file //center/d/kate/ESMG/ESMG-configs/src/MOM6/src/framework/MOM_file_parser.F90
Fortran runtime error: End of record
Program aborted. Backtrace:

One option is to have special user code for circle_obcs setting everything to zero (which was done implicitly before).

**Comment by MJHarrison-GFDL** [comment]
Yes, sorry. I forgot about circle_obcs.  We  need to code around this so
that we don't require a segment_data line in every case.

Or, should we use the same method for all segment types ? e.g.

OBC_SEGMENT_DATA = "U=value:0.0,V=value:0.0,..."

**Comment by kshedstrom** [comment]
Discuss it on Monday?

**Pull request merged**
