### PR TITLE
Mv obc initialize seg data

### PR DESCRIPTION
**Pull request by MJHarrison-GFDL**
Moves the call to initialize_segment_data from obc_config which was called from MOM_fixed_initialization to MOM_state_initialization.

### CODE REVIEW

**Comment by MJHarrison-GFDL** [comment]
Please review @NikiZadeh . As the code stands, it will only allocate space for the fields identified in the MOM_parameter file.

**Comment by MJHarrison-GFDL** [comment]
Failed in tc3.rotate:

==============================

Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:

#0  0x7f2e3bddc2ed in ???

#1  0x7f2e3bddb503 in ???

#2  0x7f2e3b458f1f in ???

#3  0x557816337c20 in __mom_open_boundary_MOD_rotate_obc_config

	at ../../../src/core/MOM_open_boundary.F90:5028

**Comment by nikizadehgfdl** [comment]
@MJHarrison-GFDL what happened with this PR? Did it not work for OBC test cases?

**Comment by MJHarrison-GFDL** [comment]
@nikizadehgfdl . Canceled and re-submitted ( https://github.com/NOAA-GFDL/MOM6/pull/1174 ). Side-effects involving rotation were causing a problem.

**Pull request closed without merging**
