### PR TITLE
User/mjh/remove extensions

### PR DESCRIPTION
**Pull request by MJHarrison-GFDL**

### CODE REVIEW

**Comment by kshedstrom** [comment]
Lol on the travis failure.

Are you aware that DOME answers changed? Also, I had to extend segments for the mini Supercritical case to get the good flow through. Otherwise, there's trouble in the NW corner.

So, I noticed that this:

```
        do j=segment%HI%jsd,segment%HI%jed
          CS%mask2dCv(i+1,J-1)=0.0
          CS%mask2dCv(i+1,J)=0.0
        enddo
```
might rather be:
```
        do J=segment%HI%JsdB,segment%HI%JedB
          CS%mask2dCv(i+1,J)=0.0
        enddo
```
I tried it and it gives the same answers for circle_obcs, a better answer for the big Supercritical.

**Comment by MJHarrison-GFDL** [comment]
I am losing it. Redundant and out of bounds - could be the latter which impacted Supercritical.  I didn't test DOME, but the answers should change.

**Comment by MJHarrison-GFDL** [comment]
I'm going to make another commit and submit a new PR

**Comment by kshedstrom** [comment]
I know I'll get grief for this, but my user/ksh/open_bc branch has it the
way I think it should be, plus the latest from GFDL. I can make a pull
request from there, but I generated the other pull request because it
shouldn't change answers.

**Pull request closed without merging**
